# Generated by Django 5.2 on 2025-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcategory',
            name='name',
            field=models.CharField(help_text='Name of the exam category. e.g: Oral exam, ECA, Practical Exam, Games and Sports, etc', max_length=100, unique=True),
        ),
    ]
